"use client";

import { CloudRain, Thermometer, Droplets, Layers, Loader2, RefreshCw, MoonStar } from "lucide-react";
import SourceBadge from "@/components/SourceBadge";
import type { EnvironmentReport } from "@/lib/api/satellite-client";

function Section({
  icon: Icon,
  title,
  badge,
  children,
}: {
  icon: typeof CloudRain;
  title: string;
  badge: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <div className="p-4 bg-farm-gray rounded-xl space-y-2">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <h4 className="text-xs font-bold text-farm-dark flex items-center gap-1.5">
          <Icon className="w-3.5 h-3.5 text-farm-green" />
          {title}
        </h4>
        {badge}
      </div>
      {children}
    </div>
  );
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <p className="text-[10px] text-farm-muted">{label}</p>
      <p className="text-sm font-bold text-farm-dark">{value}</p>
    </div>
  );
}

const mm = (v: number | null) => (v === null ? "—" : `${v.toFixed(0)} mm`);

/**
 * Rainfall (CHIRPS), land-surface temperature (MODIS), soil moisture (SMAP,
 * regional) and static soil properties (OpenLandMap) for a real farm, each
 * with its own source/date/resolution badge.
 */
export default function EnvironmentReportCard({
  report,
  isLoading,
  isError,
  onRetry,
}: {
  report: EnvironmentReport | null;
  isLoading: boolean;
  isError: boolean;
  onRetry: () => void;
}) {
  return (
    <div className="bg-white rounded-2xl border border-farm-border-color p-5 shadow-xs">
      <div className="mb-4">
        <h3 className="font-bold text-farm-dark text-sm flex items-center gap-2">
          <CloudRain className="w-4 h-4 text-sky-600" />
          Field Environment
        </h3>
        <p className="text-xs text-farm-muted">Rainfall, heat, soil moisture and soil — refreshed nightly</p>
      </div>

      {isLoading ? (
        <div className="flex items-center gap-2 text-xs text-farm-muted py-4">
          <Loader2 className="w-4 h-4 animate-spin" /> Loading environment report…
        </div>
      ) : isError ? (
        <div className="p-4 rounded-xl bg-red-50 border border-red-200 text-xs text-red-900 flex items-center justify-between gap-3">
          <span>Couldn&apos;t load the environment report.</span>
          <button
            onClick={onRetry}
            className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg border border-red-300 bg-white font-semibold hover:bg-red-100"
          >
            <RefreshCw className="w-3.5 h-3.5" /> Retry
          </button>
        </div>
      ) : !report ? (
        <div className="p-5 rounded-xl bg-farm-gray text-center text-xs text-farm-muted flex flex-col items-center gap-1.5">
          <MoonStar className="w-5 h-5" />
          <p>
            <strong className="text-farm-dark">No environment report yet.</strong> It&apos;s generated by the
            nightly refresh — check back tomorrow.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          <Section
            icon={CloudRain}
            title="Rainfall"
            badge={
              <SourceBadge
                live={{
                  source: "CHIRPS",
                  asOf: report.rainfall.provenance.as_of,
                  resolution: report.rainfall.provenance.resolution,
                }}
              />
            }
          >
            <div className="grid grid-cols-4 gap-2">
              <Stat label="7 days" value={mm(report.rainfall.mm_7d)} />
              <Stat label="30 days" value={mm(report.rainfall.mm_30d)} />
              <Stat label="90 days" value={mm(report.rainfall.mm_90d)} />
              <Stat label="Since sowing" value={mm(report.rainfall.mm_since_sowing)} />
            </div>
          </Section>

          <Section
            icon={Thermometer}
            title="Land-surface heat"
            badge={
              <SourceBadge
                live={{
                  source: "MODIS",
                  asOf: report.temperature.provenance.as_of,
                  resolution: report.temperature.provenance.resolution,
                }}
              />
            }
          >
            <div className="grid grid-cols-2 gap-2">
              <Stat
                label="Mean surface temp (60 d)"
                value={report.temperature.mean_lst_c === null ? "—" : `${report.temperature.mean_lst_c.toFixed(1)} °C`}
              />
              <Stat label="8-day periods above 35 °C" value={`${report.temperature.hot_periods_60d}`} />
            </div>
          </Section>

          <Section
            icon={Droplets}
            title="Soil moisture"
            badge={
              <SourceBadge
                live={{
                  source: "SMAP",
                  asOf: report.soil_moisture.provenance.as_of,
                  resolution: report.soil_moisture.provenance.resolution,
                }}
              />
            }
          >
            <Stat
              label="Surface soil moisture"
              value={
                report.soil_moisture.surface_moisture === null
                  ? "—"
                  : `${report.soil_moisture.surface_moisture.toFixed(2)} m³/m³`
              }
            />
          </Section>

          <Section
            icon={Layers}
            title="Soil (0–10 cm)"
            badge={
              <SourceBadge
                live={{
                  label: "Soil map",
                  source: "OpenLandMap",
                  asOf: null,
                  resolution: report.soil.provenance.resolution,
                }}
              />
            }
          >
            <div className="grid grid-cols-3 gap-2">
              <Stat label="pH (H₂O)" value={report.soil.ph === null ? "—" : report.soil.ph.toFixed(1)} />
              <Stat
                label="Organic carbon"
                value={
                  report.soil.organic_carbon_g_per_kg === null
                    ? "—"
                    : `${report.soil.organic_carbon_g_per_kg.toFixed(0)} g/kg`
                }
              />
              <Stat label="Texture" value={report.soil.texture_class ?? "—"} />
            </div>
          </Section>
        </div>
      )}
    </div>
  );
}
